### ISSUE TITLE
will this docker work with eevee rendering

### ISSUE THREAD

**Issue by pampanelson** [jtomori/docker_blender_gpu#1]
I saw the cmd line has X11 something , will it work with eevee?
thanks

**Comment by pampanelson** [comment]
I tried, eevee rendering works , but when I use the official version blender got Unable to open a display error.
maybe the blender is compiled specially ? 
and I installed the 2.80beta , but bpy.app.version_string output 2.79, the python api about cycles is 2.79 indeed

**Comment by jtomori** [comment]
Hello,
this container supports UI version of blender (and cmd). I tested it with Cycles and Eevee and it seemed to work fine, also without a noticeable performance impact. Most of the features should work well, although I haven't tested audio.

Images on docker hub are quite old builds, before 2.80 was stable. I should probably update it with recent 2.80.

When new blender is released the image needs to be added / rebuilt.

**Comment by pampanelson** [comment]
for some reason I installed blender 2.83 once,but not work .
 after I edit Dockerfile , blender 2.79 was installed again.
I guess the proble is about PPA source settings.

I added a linux version blender downloaded from blender website  into the docker, but run with the error of unable to open display when render eevee.I don't know much about nvidia cuda opengl container . I tried to install a x server into container and run it for fix the unable to open display error .
but your way is much more neat .
Could you please give instruction or point a correct direction ? 
sincerely.

**Comment by jtomori** [comment]
I am working on adding a new docker image with the latest Blender under `2.80` tag.
Right now it fails to run, but I hope to fix it soon :)

**Comment by pampanelson** [comment]
thanks bro

**Comment by jtomori** [comment]
Ok, I managed to build the latest blender and from quick testing it seems to work fine. Give it a try and let me know if you run into any issues. You can use `2.80` or `latest` tags.
It should be built on docker hub in the next minutes.

If you will want a more recent version in the future then just ping me and I will trigger re-build of the image.

**Comment by pampanelson** [comment]
blender version output is 2.83 , but I had the error :
Home directory not accessible: Permission denied
and with --privileged=true got the same error

**Comment by jtomori** [comment]
How did you get the error?
Some functions might not work, like saving user preferences, because your user doesn't exist in the container. But you can save and open scenes from mounted drive: `/mnt/blender`.

Make sure to use this command to run Blender: `docker run --runtime=nvidia -it --rm -e DISPLAY -u $(id -u):$(id -g) -v /tmp/.X11-unix:/tmp/.X11-unix -v "$(pwd)":/tmp/blender jtomori/blender_gpu:latest`

**Comment by pampanelson** [comment]
here is output : 


docker run --runtime=nvidia -it --rm -e DISPLAY -u $(id -u):$(id -g) -v /tmp/.X11-unix:/tmp/.X11-unix -v "$(pwd)":/tmp/blender jtomori/blender_gpu:latest bash
groups: cannot find name for group ID 1000
I have no name!@43ed697bbdf1:/tmp/blender$ blender -b --python-console
Blender 2.83 (sub 4)
Home directory not accessible: Permission denied
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Writing: /tmp/blender.crash.txt
Segmentation fault (core dumped)
I have no name!@43ed697bbdf1:/tmp/blender$ cat /tmp/blender.crash.txt
# Blender 2.83 (sub 4), Unknown revision

# backtrace
/usr/lib/blender/blender(BLI_system_backtrace+0x33) [0x55fbf98ef033]
/usr/lib/blender/blender(+0x139d99f) [0x55fbf727199f]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f358be50f20]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(PyModule_GetState+0xb) [0x7f358f5ed6ab]
/usr/lib/python3.7/lib-dynload/readline.cpython-37m-x86_64-linux-gnu.so(+0x4220) [0x7f355e5fa220]
/usr/lib/x86_64-linux-gnu/libedit.so.2(rl_initialize+0x4e1) [0x7f357a052441]
/usr/lib/python3.7/lib-dynload/readline.cpython-37m-x86_64-linux-gnu.so(PyInit_readline+0x1b7) [0x7f355e5fa0f7]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyImport_LoadDynamicModuleWithSpec+0x183) [0x7f358f53ebe3]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x18515b) [0x7f358f53f15b]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x1d8) [0x7f358f62e0f8]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x25) [0x7f358f62ec55]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7af0) [0x7f358f42f370]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x996) [0x7f358f557356]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x93) [0x7f358f62e333]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x8445) [0x7f358f42fcc5]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x9344) [0x7f358f430bc4]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x5d18) [0x7f358f42d598]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x5d18) [0x7f358f42d598]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x5d18) [0x7f358f42d598]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x2e2) [0x7f358f62e752]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x275f70) [0x7f358f62ff70]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyObject_CallMethodIdObjArgs+0xa9) [0x7f358f630599]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(PyImport_ImportModuleLevelObject+0x5ff) [0x7f358f43a29f]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x72ca) [0x7f358f42eb4a]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x77f43) [0x7f358f431f43]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x8445) [0x7f358f42fcc5]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x996) [0x7f358f557356]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(PyEval_EvalCodeEx+0x3e) [0x7f358f5575de]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(PyEval_EvalCode+0x1b) [0x7f358f5583ab]
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(PyRun_StringFlags+0x8b) [0x7f358f52605b]
/usr/lib/blender/blender(BPY_execute_string_ex+0x108) [0x55fbf7725118]
/usr/lib/blender/blender(+0x139b394) [0x55fbf726f394]
/usr/lib/blender/blender(BLI_argsParse+0xda) [0x55fbf988f0ca]
/usr/lib/blender/blender(main+0x2a3) [0x55fbf7215273]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f358be33b97]
/usr/lib/blender/blender(_start+0x2a) [0x55fbf726dfea]

**Comment by pampanelson** [comment]
if I run it on a ubuntu 18.04 destop in gui mode , gui will pop up  and works.
but bash mode and command mode don't work just like run via remote ssh.
I'm working on a project of cluster blender render farm , so my goal is to run the blender eevee render on a headless server with nvidia gpu.

**Comment by jtomori** [comment]
I see, thanks for reporting this, I created a separate issue for that: #2
